# Generated by Django 5.0.6 on 2025-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone (apenas números)'),
        ),
    ]
