# render.yaml

services:

# Banco de Dados PostgreSQL (Criado separadamente)
# Você pode adicionar sua configuração de banco aqui se necessário

# Redis gerenciado pelo Render
- type: redis
  name: valuation-redis
  plan: free
  region: oregon
  ipAllowList: []

# Aplicação Web Django
- type: web
  name: valuation-web
  plan: free
  runtime: docker
  dockerfilePath: ./Dockerfile.web
  dockerContext: .
  healthCheckPath: /
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: REDIS_URL
      fromService: { type: redis, name: valuation-redis, property: connectionString }
    - key: CELERY_BROKER_URL
      fromService: { type: redis, name: valuation-redis, property: connectionString }
    - key: DJANGO_SETTINGS_MODULE
      value: valuation.settings # Ajuste o nome se sua pasta for diferente
    - key: PYTHONUNBUFFERED
      value: "1"
    - key: PYTHONDONTWRITEBYTECODE
      value: "1"
    - key: SECRET_KEY
      sync: false
    - key: GEMINI_API_KEY
      sync: false
    - key: GAMMA_API_KEY
      sync: false
    - key: DEBUG
      value: "False"
    - key: DJANGO_ALLOWED_HOSTS
      sync: false
    - key: DJANGO_CSRF_TRUSTED_ORIGINS
      sync: false
  buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
  # Se estiver usando staticPublishPath, adicione:
  # staticPublishPath: staticfiles_build

# Worker do Celery para tarefas assíncronas (deixe igual ao web no que importa)
- type: worker
  name: valuation-celery
  plan: free
  runtime: docker
  dockerfilePath: ./Dockerfile.worker
  dockerContext: .
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: REDIS_URL
      fromService: { type: redis, name: valuation-redis, property: connectionString }
    - key: CELERY_BROKER_URL
      fromService: { type: redis, name: valuation-redis, property: connectionString }
    - key: DJANGO_SETTINGS_MODULE
      value: valuation.settings
    - key: PYTHONUNBUFFERED
      value: "1"
    - key: PYTHONDONTWRITEBYTECODE
      value: "1"
    - key: SECRET_KEY
      sync: false
    - key: GEMINI_API_KEY
      sync: false
    - key: GAMMA_API_KEY
      sync: false
