# render.yaml (v6 - Usando DB externo criado manualmente)
services:
  # --- NÃO DEFINIMOS MAIS O BANCO DE DADOS AQUI ---

  # 2. Cache Redis Gerenciado pelo Render (Ainda via Blueprint)
  - type: redis
    name: valuation-redis
    plan: free
    region: oregon
    ipAllowList: []

  # 3. Aplicação Web Django (Gunicorn via Docker)
  - type: web
    name: valuation-web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      # --- VARIÁVEL PARA O BANCO DE DADOS EXTERNO ---
      - key: DATABASE_URL
        sync: false # DEFINIREMOS NO DASHBOARD COM A URL INTERNA
      # --- FIM DA VARIÁVEL DO BANCO ---
      - key: REDIS_URL
        fromService: # Redis ainda é criado via Blueprint
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      # --- Restante das envVars do Web ---
      - key: DJANGO_SETTINGS_MODULE
        value: valuation.settings # Verifique o nome da pasta do projeto
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
    buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn valuation.wsgi:application --bind 0.0.0.0:$PORT"

  # 4. Worker do Celery (Background via Docker)
  - type: worker
    name: valuation-celery
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # --- VARIÁVEL PARA O BANCO DE DADOS EXTERNO ---
      - key: DATABASE_URL
        sync: false # DEFINIREMOS NO DASHBOARD COM A URL INTERNA
      # --- FIM DA VARIÁVEL DO BANCO ---
      - key: REDIS_URL
        fromService: # Redis ainda é criado via Blueprint
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      # --- Restante das envVars do Celery ---
      - key: DJANGO_SETTINGS_MODULE
        value: valuation.settings # Verifique o nome da pasta do projeto
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
    startCommand: "celery -A valuation worker --loglevel=info"