# render.yaml (v7 - Removed startCommand for Docker runtime)
services:
  # 1. Banco de Dados PostgreSQL (Criado manualmente)
  # ... (Banco de dados já foi criado separadamente) ...

  # 2. Cache Redis Gerenciado pelo Render
  - type: redis
    name: valuation-redis
    plan: free
    region: oregon # Use a região onde criou o DB
    ipAllowList: []

  # 3. Aplicação Web Django (Gunicorn via Docker)
  - type: web
    name: valuation-web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false # Definido no Dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: valuation.settings # Verifique o nome da pasta do projeto
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
    buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
    # startCommand: REMOVIDO DAQUI

  # 4. Worker do Celery (Background via Docker)
  - type: worker
    name: valuation-celery
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false # Definido no Dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: valuation.settings # Verifique o nome da pasta do projeto
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
    # startCommand: REMOVIDO DAQUI