# render.yaml (v4 - Corrected type to 'postgres')
services:
  # 1. Banco de Dados PostgreSQL Gerenciado pelo Render
  - type: postgres         # CORRIGIDO de psql
    name: valuation-db
    plan: free
    region: oregon        # Mantendo região (bom ter)
    databaseName: valuation_db
    user: valuation_user
    ipAllowList: []

  # 2. Cache Redis Gerenciado pelo Render
  - type: redis
    name: valuation-redis
    plan: free
    region: oregon
    ipAllowList: []

  # 3. Aplicação Web Django (Gunicorn via Docker)
  - type: web
    name: valuation-web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres   # CORRIGIDO de psql
          name: valuation-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      # --- Restante das envVars do Web ---
      - key: DJANGO_SETTINGS_MODULE
        # Verifique se 'valuation' é o nome correto da pasta do seu projeto Django
        value: valuation.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
    buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn valuation.wsgi:application --bind 0.0.0.0:$PORT"

  # 4. Worker do Celery (Background via Docker)
  - type: worker
    name: valuation-celery
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres   # CORRIGIDO de psql
          name: valuation-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: valuation-redis
          property: connectionString
      # --- Restante das envVars do Celery ---
      - key: DJANGO_SETTINGS_MODULE
        # Verifique se 'valuation' é o nome correto
        value: valuation.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GAMMA_API_KEY
        sync: false
    startCommand: "celery -A valuation worker --loglevel=info"